name: Send CSV to Telegram

on:
  workflow_dispatch: # Allow manual trigger
  schedule:
    - cron: "0 1 * * 1-5" # weekday 08:00 WIB
    - cron: "0 8 * * 1-5" # weekday 15:00 WIB

jobs:
  send_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scanner.py
